spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/doglover;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      platform: h2
      data-locations: classpath:data.sql
      mode: always


  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.SQL: debug